In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x+2
z = y*y+3
out = z.mean()

print(y)
print(z)
print(out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)
tensor(12., grad_fn=<MeanBackward0>)


In [4]:
out.backward()

In [5]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [6]:
with torch.no_grad():
    k = x+1
    print(k)

tensor([[2., 2.],
        [2., 2.]])
