In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Net(nn.Module):
    def __init__(self): # 定義神經網路結構, 輸入數據 1x32x32
        super(Net, self).__init__()
        # 第一層(卷基層)
        self.conv1 = nn.Conv2d(1, 6, 3) # 輸入頻道1, 輸出頻道6, 卷積3x3
        # 第二層(卷基層)
        self.conv2 = nn.Conv2d(6, 16, 3) # 輸入頻道6, 輸出頻道16, 卷積3x3
        # 第三層(全連接層)
        self.fc1 = nn.Linear(16*28*28, 512) # 輸入維度16x28x28=12544, 輸出維度512
        # 第四層(全連接層)
        self.fc2 = nn.Linear(512, 64) # 輸入維度512, 輸出維度64
        # 第五層(全連接層)
        self.fc3 = nn.Linear(64, 2) # 輸入維度64, 輸出維度2

    def forward(self, x): # 定義數據流向
        x = self.conv1(x)
        x = F.relu(x)

        x = self.conv2(x)
        x = F.relu(x)

        x = x.view(-1, 16*28*28) # view=>重定型
        x = self.fc1(x)
        x = F.relu(x)

        x = self.fc2(x)
        x = F.relu(x)

        x = self.fc3(x)
        
        return x

In [3]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)


In [4]:
# 生成隨機輸入
input_data = torch.randn(1, 1, 32, 32)
print(input_data)
print(input_data.size())

tensor([[[[ 1.1699,  0.5318,  0.0310,  ...,  0.0826,  1.4423,  0.1712],
          [ 0.8501, -0.3419, -1.9022,  ...,  0.7012, -0.6594,  1.0875],
          [ 0.7678,  0.4926,  0.8041,  ..., -0.7597,  0.9030,  0.0817],
          ...,
          [ 0.9678,  0.2502,  0.1481,  ...,  0.8088,  0.5563,  0.2808],
          [-0.4016,  0.4271, -0.1602,  ...,  0.5440, -0.2007,  1.7349],
          [-0.5594,  0.9364, -1.7363,  ...,  1.6732, -0.6525, -0.5336]]]])
torch.Size([1, 1, 32, 32])


In [7]:
# 運行神經網路
out = net(input_data)
print(out)
print(out.size())

tensor([[0.0545, 0.0632]], grad_fn=<AddmmBackward>)
torch.Size([1, 2])


In [24]:
# 隨機生成真實值
target = torch.randn(2)
target = target.view(1, -1)
print(target)

tensor([[ 0.8367, -0.8170]])


In [25]:
criterion = nn.L1Loss() # 絕對誤差平均值
loss = criterion(out, target)
print(loss)

tensor(0.8312, grad_fn=<L1LossBackward>)


In [26]:
# 反向傳遞
net.zero_grad() # 清零梯度
loss.backward() # 自動計算梯度, 反向傳遞

In [28]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.step()

In [29]:
out = net(input_data)
print(out)
print(out.size())

tensor([[0.0926, 0.0315]], grad_fn=<AddmmBackward>)
torch.Size([1, 2])


In [30]:
criterion = nn.L1Loss() # 絕對誤差平均值
loss = criterion(out, target)
print(loss)

tensor(0.7963, grad_fn=<L1LossBackward>)
